//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_des_reservations
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int NumRes { get; set; }
        public int NumeroType { get; set; }
        public int CodeClient { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual TypeHebergement TypeHebergement { get; set; }
    }
}
