//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_des_reservations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RiadEntities : DbContext
    {
        public RiadEntities()
            : base("name=RiadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Reservation> Reservation { get; set; }
        public virtual DbSet<Riad> Riad { get; set; }
        public virtual DbSet<TypeHebergement> TypeHebergement { get; set; }
        public virtual DbSet<Negocier> Negocier { get; set; }
    }
}
