//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_des_reservations
{
    using System;
    using System.Collections.Generic;
    
    public partial class Riad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Riad()
        {
            this.Negocier = new HashSet<Negocier>();
        }
    
        public int NumeroR { get; set; }
        public string NomR { get; set; }
        public string AdresseRueR { get; set; }
        public string CodePostaleR { get; set; }
        public string VilleR { get; set; }
        public string TelephoneR { get; set; }
        public string NomContactR { get; set; }
        public string CodeReg { get; set; }
        public int NombreDePlaces { get; set; }
    
        public virtual Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negocier> Negocier { get; set; }
    }
}
